security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ENSEIGNANT:       ROLE_USER
        ROLE_ETUDIANT:       ROLE_USER
        ROLE_CHEFENTREPRISE: ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                success_handler: redirect.after.login
            logout:      
                target: /home
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_SUPER_ADMIN}
        - { path: ^/homeAd/, role: ROLE_ADMIN}        
        - { path: ^/homeEns, role: ROLE_ENSEIGNANT }
        - { path: ^/uploadcours, role: ROLE_ENSEIGNANT }
        - { path: ^/homeEt, role: ROLE_ETUDIANT }
        - { path: ^/homeCh, role: ROLE_CHEFENTREPRISE }
