quizquestion:
    path:     /
    defaults: { _controller: "MyAppUlearnBundle:QuizQuestion:index" }

quizquestion_show:
    path:     /{id}/show
    defaults: { _controller: "MyAppUlearnBundle:QuizQuestion:show" }

quizquestion_new:
    path:     /new
    defaults: { _controller: "MyAppUlearnBundle:QuizQuestion:new" }

quizquestion_create:
    path:     /create
    defaults: { _controller: "MyAppUlearnBundle:QuizQuestion:create" }
    methods:  POST

quizquestion_edit:
    path:     /{id}/edit
    defaults: { _controller: "MyAppUlearnBundle:QuizQuestion:edit" }

quizquestion_update:
    path:     /{id}/update
    defaults: { _controller: "MyAppUlearnBundle:QuizQuestion:update" }
    methods:  [POST, PUT]

quizquestion_delete:
    path:     /{id}/delete
    defaults: { _controller: "MyAppUlearnBundle:QuizQuestion:delete" }
    methods:  [POST, DELETE]
