services:
    sonata.admin.User:
        class: Admin\AdminBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "User" }
        arguments:
            - ~
            - Admin\AdminBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [AdminAdminBundle]]
            
    sonata.admin.Faq:
        class: Admin\AdminBundle\Admin\FaqAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Faq" }
        arguments:
            - ~
            - Admin\AdminBundle\Entity\Faq
            - ~
        calls:
            - [ setTranslationDomain, [AdminAdminBundle]]        