Module:
    type: entity
    table: module
    id:
        idmodule:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: idModule
            generator:
                strategy: IDENTITY
    fields:
        nommodule:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            column: nomModule
    lifecycleCallbacks: {  }
