<?php

namespace Proxies\__CG__\MyApp\UlearnBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Certification extends \MyApp\UlearnBundle\Entity\Certification implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Certification' . "\0" . 'idcertification', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Certification' . "\0" . 'duree', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Certification' . "\0" . 'datepassage', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Certification' . "\0" . 'nomcertif', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Certification' . "\0" . 'idadmin', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Certification' . "\0" . 'idetudiant');
        }

        return array('__isInitialized__', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Certification' . "\0" . 'idcertification', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Certification' . "\0" . 'duree', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Certification' . "\0" . 'datepassage', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Certification' . "\0" . 'nomcertif', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Certification' . "\0" . 'idadmin', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Certification' . "\0" . 'idetudiant');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Certification $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdcertification()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdcertification();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcertification', array());

        return parent::getIdcertification();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuree($duree)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuree', array($duree));

        return parent::setDuree($duree);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuree()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuree', array());

        return parent::getDuree();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatepassage($datepassage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatepassage', array($datepassage));

        return parent::setDatepassage($datepassage);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatepassage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatepassage', array());

        return parent::getDatepassage();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomcertif($nomcertif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomcertif', array($nomcertif));

        return parent::setNomcertif($nomcertif);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomcertif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomcertif', array());

        return parent::getNomcertif();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdadmin(\Admin\AdminBundle\Entity\User $idadmin = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdadmin', array($idadmin));

        return parent::setIdadmin($idadmin);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdadmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdadmin', array());

        return parent::getIdadmin();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdetudiant(\Admin\AdminBundle\Entity\User $idetudiant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdetudiant', array($idetudiant));

        return parent::addIdetudiant($idetudiant);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdetudiant(\Admin\AdminBundle\Entity\User $idetudiant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdetudiant', array($idetudiant));

        return parent::removeIdetudiant($idetudiant);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdetudiant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdetudiant', array());

        return parent::getIdetudiant();
    }

}
