<?php

namespace Proxies\__CG__\MyApp\UlearnBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cours extends \MyApp\UlearnBundle\Entity\Cours implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Cours' . "\0" . 'idcours', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Cours' . "\0" . 'date', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Cours' . "\0" . 'nomcours', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Cours' . "\0" . 'valider', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Cours' . "\0" . 'chemincours', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Cours' . "\0" . 'idmodule', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Cours' . "\0" . 'idresponsable', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Cours' . "\0" . 'idenseignant', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Cours' . "\0" . 'idetudiant');
        }

        return array('__isInitialized__', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Cours' . "\0" . 'idcours', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Cours' . "\0" . 'date', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Cours' . "\0" . 'nomcours', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Cours' . "\0" . 'valider', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Cours' . "\0" . 'chemincours', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Cours' . "\0" . 'idmodule', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Cours' . "\0" . 'idresponsable', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Cours' . "\0" . 'idenseignant', '' . "\0" . 'MyApp\\UlearnBundle\\Entity\\Cours' . "\0" . 'idetudiant');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cours $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdcours()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdcours();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcours', array());

        return parent::getIdcours();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomcours($nomcours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomcours', array($nomcours));

        return parent::setNomcours($nomcours);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomcours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomcours', array());

        return parent::getNomcours();
    }

    /**
     * {@inheritDoc}
     */
    public function setValider($valider)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValider', array($valider));

        return parent::setValider($valider);
    }

    /**
     * {@inheritDoc}
     */
    public function getValider()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValider', array());

        return parent::getValider();
    }

    /**
     * {@inheritDoc}
     */
    public function setChemincours($chemincours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChemincours', array($chemincours));

        return parent::setChemincours($chemincours);
    }

    /**
     * {@inheritDoc}
     */
    public function getChemincours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChemincours', array());

        return parent::getChemincours();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdmodule(\MyApp\UlearnBundle\Entity\Module $idmodule = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdmodule', array($idmodule));

        return parent::setIdmodule($idmodule);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdmodule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmodule', array());

        return parent::getIdmodule();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdresponsable(\University\UserBundle\Entity\User $idresponsable = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdresponsable', array($idresponsable));

        return parent::setIdresponsable($idresponsable);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdresponsable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdresponsable', array());

        return parent::getIdresponsable();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdenseignant(\University\UserBundle\Entity\User $idenseignant = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdenseignant', array($idenseignant));

        return parent::setIdenseignant($idenseignant);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdenseignant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdenseignant', array());

        return parent::getIdenseignant();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdetudiant(\University\UserBundle\Entity\User $idetudiant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdetudiant', array($idetudiant));

        return parent::addIdetudiant($idetudiant);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdetudiant(\University\UserBundle\Entity\User $idetudiant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdetudiant', array($idetudiant));

        return parent::removeIdetudiant($idetudiant);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdetudiant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdetudiant', array());

        return parent::getIdetudiant();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
